/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardDashboardRouteImport } from './routes/_dashboard/dashboard'
import { Route as DashboardDashboardIndexRouteImport } from './routes/_dashboard/dashboard/index'
import { Route as DashboardDashboardGroupsRouteImport } from './routes/_dashboard/dashboard/groups'
import { Route as DashboardDashboardGroupDetailRouteImport } from './routes/_dashboard/dashboard/_group-detail'
import { Route as DashboardDashboardSettingsIndexRouteImport } from './routes/_dashboard/dashboard/settings/index'
import { Route as DashboardDashboardGroupDetailGroupsSettleupIndexRouteImport } from './routes/_dashboard/dashboard/_group-detail/groups/settleup/index'
import { Route as DashboardDashboardGroupDetailGroupsExpenseIndexRouteImport } from './routes/_dashboard/dashboard/_group-detail/groups/expense/index'
import { Route as DashboardDashboardGroupDetailGroupsGroupIdGroupIdRouteImport } from './routes/_dashboard/dashboard/_group-detail/groups/_groupId/$groupId'
import { Route as DashboardDashboardGroupDetailGroupsGroupIdBalancesIndexRouteImport } from './routes/_dashboard/dashboard/_group-detail/groups/_groupId/balances/index'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDashboardRoute = DashboardDashboardRouteImport.update({
  id: '/_dashboard/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDashboardIndexRoute = DashboardDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardDashboardRoute,
} as any)
const DashboardDashboardGroupsRoute =
  DashboardDashboardGroupsRouteImport.update({
    id: '/groups',
    path: '/groups',
    getParentRoute: () => DashboardDashboardRoute,
  } as any)
const DashboardDashboardGroupDetailRoute =
  DashboardDashboardGroupDetailRouteImport.update({
    id: '/_group-detail',
    getParentRoute: () => DashboardDashboardRoute,
  } as any)
const DashboardDashboardSettingsIndexRoute =
  DashboardDashboardSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => DashboardDashboardRoute,
  } as any)
const DashboardDashboardGroupDetailGroupsSettleupIndexRoute =
  DashboardDashboardGroupDetailGroupsSettleupIndexRouteImport.update({
    id: '/groups/settleup/',
    path: '/groups/settleup/',
    getParentRoute: () => DashboardDashboardGroupDetailRoute,
  } as any)
const DashboardDashboardGroupDetailGroupsExpenseIndexRoute =
  DashboardDashboardGroupDetailGroupsExpenseIndexRouteImport.update({
    id: '/groups/expense/',
    path: '/groups/expense/',
    getParentRoute: () => DashboardDashboardGroupDetailRoute,
  } as any)
const DashboardDashboardGroupDetailGroupsGroupIdGroupIdRoute =
  DashboardDashboardGroupDetailGroupsGroupIdGroupIdRouteImport.update({
    id: '/groups/_groupId/$groupId',
    path: '/groups/$groupId',
    getParentRoute: () => DashboardDashboardGroupDetailRoute,
  } as any)
const DashboardDashboardGroupDetailGroupsGroupIdBalancesIndexRoute =
  DashboardDashboardGroupDetailGroupsGroupIdBalancesIndexRouteImport.update({
    id: '/groups/_groupId/balances/',
    path: '/groups/balances/',
    getParentRoute: () => DashboardDashboardGroupDetailRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof DashboardDashboardGroupDetailRouteWithChildren
  '/dashboard/groups': typeof DashboardDashboardGroupsRoute
  '/dashboard/': typeof DashboardDashboardIndexRoute
  '/dashboard/settings': typeof DashboardDashboardSettingsIndexRoute
  '/dashboard/groups/$groupId': typeof DashboardDashboardGroupDetailGroupsGroupIdGroupIdRoute
  '/dashboard/groups/expense': typeof DashboardDashboardGroupDetailGroupsExpenseIndexRoute
  '/dashboard/groups/settleup': typeof DashboardDashboardGroupDetailGroupsSettleupIndexRoute
  '/dashboard/groups/balances': typeof DashboardDashboardGroupDetailGroupsGroupIdBalancesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof DashboardDashboardIndexRoute
  '/dashboard/groups': typeof DashboardDashboardGroupsRoute
  '/dashboard/settings': typeof DashboardDashboardSettingsIndexRoute
  '/dashboard/groups/$groupId': typeof DashboardDashboardGroupDetailGroupsGroupIdGroupIdRoute
  '/dashboard/groups/expense': typeof DashboardDashboardGroupDetailGroupsExpenseIndexRoute
  '/dashboard/groups/settleup': typeof DashboardDashboardGroupDetailGroupsSettleupIndexRoute
  '/dashboard/groups/balances': typeof DashboardDashboardGroupDetailGroupsGroupIdBalancesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/register': typeof RegisterRoute
  '/_dashboard/dashboard': typeof DashboardDashboardRouteWithChildren
  '/_dashboard/dashboard/_group-detail': typeof DashboardDashboardGroupDetailRouteWithChildren
  '/_dashboard/dashboard/groups': typeof DashboardDashboardGroupsRoute
  '/_dashboard/dashboard/': typeof DashboardDashboardIndexRoute
  '/_dashboard/dashboard/settings/': typeof DashboardDashboardSettingsIndexRoute
  '/_dashboard/dashboard/_group-detail/groups/_groupId/$groupId': typeof DashboardDashboardGroupDetailGroupsGroupIdGroupIdRoute
  '/_dashboard/dashboard/_group-detail/groups/expense/': typeof DashboardDashboardGroupDetailGroupsExpenseIndexRoute
  '/_dashboard/dashboard/_group-detail/groups/settleup/': typeof DashboardDashboardGroupDetailGroupsSettleupIndexRoute
  '/_dashboard/dashboard/_group-detail/groups/_groupId/balances/': typeof DashboardDashboardGroupDetailGroupsGroupIdBalancesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/logout'
    | '/register'
    | '/dashboard'
    | '/dashboard/groups'
    | '/dashboard/'
    | '/dashboard/settings'
    | '/dashboard/groups/$groupId'
    | '/dashboard/groups/expense'
    | '/dashboard/groups/settleup'
    | '/dashboard/groups/balances'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/logout'
    | '/register'
    | '/dashboard'
    | '/dashboard/groups'
    | '/dashboard/settings'
    | '/dashboard/groups/$groupId'
    | '/dashboard/groups/expense'
    | '/dashboard/groups/settleup'
    | '/dashboard/groups/balances'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/login'
    | '/logout'
    | '/register'
    | '/_dashboard/dashboard'
    | '/_dashboard/dashboard/_group-detail'
    | '/_dashboard/dashboard/groups'
    | '/_dashboard/dashboard/'
    | '/_dashboard/dashboard/settings/'
    | '/_dashboard/dashboard/_group-detail/groups/_groupId/$groupId'
    | '/_dashboard/dashboard/_group-detail/groups/expense/'
    | '/_dashboard/dashboard/_group-detail/groups/settleup/'
    | '/_dashboard/dashboard/_group-detail/groups/_groupId/balances/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  RegisterRoute: typeof RegisterRoute
  DashboardDashboardRoute: typeof DashboardDashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/dashboard': {
      id: '/_dashboard/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/dashboard/': {
      id: '/_dashboard/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardDashboardIndexRouteImport
      parentRoute: typeof DashboardDashboardRoute
    }
    '/_dashboard/dashboard/groups': {
      id: '/_dashboard/dashboard/groups'
      path: '/groups'
      fullPath: '/dashboard/groups'
      preLoaderRoute: typeof DashboardDashboardGroupsRouteImport
      parentRoute: typeof DashboardDashboardRoute
    }
    '/_dashboard/dashboard/_group-detail': {
      id: '/_dashboard/dashboard/_group-detail'
      path: ''
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardDashboardGroupDetailRouteImport
      parentRoute: typeof DashboardDashboardRoute
    }
    '/_dashboard/dashboard/settings/': {
      id: '/_dashboard/dashboard/settings/'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardDashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardDashboardRoute
    }
    '/_dashboard/dashboard/_group-detail/groups/settleup/': {
      id: '/_dashboard/dashboard/_group-detail/groups/settleup/'
      path: '/groups/settleup'
      fullPath: '/dashboard/groups/settleup'
      preLoaderRoute: typeof DashboardDashboardGroupDetailGroupsSettleupIndexRouteImport
      parentRoute: typeof DashboardDashboardGroupDetailRoute
    }
    '/_dashboard/dashboard/_group-detail/groups/expense/': {
      id: '/_dashboard/dashboard/_group-detail/groups/expense/'
      path: '/groups/expense'
      fullPath: '/dashboard/groups/expense'
      preLoaderRoute: typeof DashboardDashboardGroupDetailGroupsExpenseIndexRouteImport
      parentRoute: typeof DashboardDashboardGroupDetailRoute
    }
    '/_dashboard/dashboard/_group-detail/groups/_groupId/$groupId': {
      id: '/_dashboard/dashboard/_group-detail/groups/_groupId/$groupId'
      path: '/groups/$groupId'
      fullPath: '/dashboard/groups/$groupId'
      preLoaderRoute: typeof DashboardDashboardGroupDetailGroupsGroupIdGroupIdRouteImport
      parentRoute: typeof DashboardDashboardGroupDetailRoute
    }
    '/_dashboard/dashboard/_group-detail/groups/_groupId/balances/': {
      id: '/_dashboard/dashboard/_group-detail/groups/_groupId/balances/'
      path: '/groups/balances'
      fullPath: '/dashboard/groups/balances'
      preLoaderRoute: typeof DashboardDashboardGroupDetailGroupsGroupIdBalancesIndexRouteImport
      parentRoute: typeof DashboardDashboardGroupDetailRoute
    }
  }
}

interface DashboardDashboardGroupDetailRouteChildren {
  DashboardDashboardGroupDetailGroupsGroupIdGroupIdRoute: typeof DashboardDashboardGroupDetailGroupsGroupIdGroupIdRoute
  DashboardDashboardGroupDetailGroupsExpenseIndexRoute: typeof DashboardDashboardGroupDetailGroupsExpenseIndexRoute
  DashboardDashboardGroupDetailGroupsSettleupIndexRoute: typeof DashboardDashboardGroupDetailGroupsSettleupIndexRoute
  DashboardDashboardGroupDetailGroupsGroupIdBalancesIndexRoute: typeof DashboardDashboardGroupDetailGroupsGroupIdBalancesIndexRoute
}

const DashboardDashboardGroupDetailRouteChildren: DashboardDashboardGroupDetailRouteChildren =
  {
    DashboardDashboardGroupDetailGroupsGroupIdGroupIdRoute:
      DashboardDashboardGroupDetailGroupsGroupIdGroupIdRoute,
    DashboardDashboardGroupDetailGroupsExpenseIndexRoute:
      DashboardDashboardGroupDetailGroupsExpenseIndexRoute,
    DashboardDashboardGroupDetailGroupsSettleupIndexRoute:
      DashboardDashboardGroupDetailGroupsSettleupIndexRoute,
    DashboardDashboardGroupDetailGroupsGroupIdBalancesIndexRoute:
      DashboardDashboardGroupDetailGroupsGroupIdBalancesIndexRoute,
  }

const DashboardDashboardGroupDetailRouteWithChildren =
  DashboardDashboardGroupDetailRoute._addFileChildren(
    DashboardDashboardGroupDetailRouteChildren,
  )

interface DashboardDashboardRouteChildren {
  DashboardDashboardGroupDetailRoute: typeof DashboardDashboardGroupDetailRouteWithChildren
  DashboardDashboardGroupsRoute: typeof DashboardDashboardGroupsRoute
  DashboardDashboardIndexRoute: typeof DashboardDashboardIndexRoute
  DashboardDashboardSettingsIndexRoute: typeof DashboardDashboardSettingsIndexRoute
}

const DashboardDashboardRouteChildren: DashboardDashboardRouteChildren = {
  DashboardDashboardGroupDetailRoute:
    DashboardDashboardGroupDetailRouteWithChildren,
  DashboardDashboardGroupsRoute: DashboardDashboardGroupsRoute,
  DashboardDashboardIndexRoute: DashboardDashboardIndexRoute,
  DashboardDashboardSettingsIndexRoute: DashboardDashboardSettingsIndexRoute,
}

const DashboardDashboardRouteWithChildren =
  DashboardDashboardRoute._addFileChildren(DashboardDashboardRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  RegisterRoute: RegisterRoute,
  DashboardDashboardRoute: DashboardDashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
